@echo off
echo Activating virtual environment...
call .venv\Scripts\activate
echo Installing dependencies...
python -m pip install requests schedule
echo Starting Flask server...
echo Starting backup script in the background...
start "Backup" /B python backup.py
echo Starting Flask server...
python -m flask run --debug --host=0.0.0.0